version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB:       "dev_db"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
     image: springboot/license-service:demo
     ports:
       - "8080:8080"
     environment:
       PROFILE: "dev"
       CONFIGSERVER_URI: "http://configurationserver:8888"
       CONFIGSERVER_PORT:   "8888"
       DATABASESERVER_PORT: "5432"